#!/usr/bin/env sh

# Global variables
pager="less -s"
sura_file="sura.txt"

# check if $HOME/.local/share/ exists
if [ -f "$HOME/.local/share/Quran/Quran.txt" ]; then
	file_dir="$HOME/.local/share/Quran/Quran.txt"
elif [ -f "Quran.txt" ]; then
	file_dir="Quran.txt"
else
	echo "file Quran.txt file not found" && \
		return 1
fi

# functions begin

# variable names
usage() {
	echo
	echo "Usage:"
	echo "-l or --list     = List of Sura"
	echo "-s or --search   = Search for a keyword"
	echo "-eg or --example = print out some examples"
	echo "-h or --help     = print out this help message"
	echo "Example: Quran -h"
	echo
	exit
}

# Different examples
example() {
	echo
	echo "Quran kahf       =  Will print out the complete Sura Kahf"
	echo "Quran 18         =  Will print out the 18th Sura in The Holy Quran"
	echo "Quran kahf:10    =  Will print out the 10th verse of Sura Kahf"
	echo "Quran 18:10      =  Will print out the 10th verse of 18th Sura in The Holy Quran"
	echo "Quran kahf:1-10  =  Will print out the verse 1 to 10 of Sura kahf"
	echo "Quran 18:1-10    =  Will print out the 1 to 10 verse of the 18th Sura in The Holy Quran"
	echo "Quran falaq-naas =  Will print out Sura Falaq to Sura Naas"
	echo "Quran 113-114    =  Will print out the 113th to 114th Sura in The Holy Quran"
	echo
}

# Loop through verses

verse_loop() {
echo "With The Name Of Allah, The Most Merciful, The Most Gracious" >> $sura_file
while [ "$from" -le "$to" ]; do
	grep "\[$chapter:$from\]" $file_dir | \
		sed 's/^\[.*:\(.*\)\]\s\(.*\)/\n\n[\1] \2/g' >> $sura_file
	from="$(( $from + 1 ))"
done
}

# Loop through chapters

chapter_loop() {
	while [ "$schapter" -le "$echapter" ]; do
		grep -w3 "\[$schapter:*" $file_dir | \
			sed 's/^\[\(.*\)\]\s\(.*\)/\n\n[\1] \2/g' >> $sura_file
		schapter="$(( $schapter + 1 ))"
	done
}

# opening grace message

opening_msg() {
	echo "With the name of Allah, The Most Merciful. The Most Gracious" >> $sura_file
	echo " " >> $sura_file
}
# functions end

# case statements

case "$1" in
	""|" " ) # print usage message if first argument is empty
		usage
		;;
	-s|--search ) # search parameter/argument
		
		# if search keyword is empty, exit with exit status 1
		[ -z "$2" ] && \
			echo "empty search keyword" && \
			return 1
		
		# if search keyword is non-empty
		grep -i "$2" $file_dir | \
			sed 's/^\[\(.*\)\]\s\(.*\)/\n\n[\1] \2/g' | \
			$pager -p "$2"
		;;
	-h|--help ) # prints help message/usage
		usage
		;;
	-eg|--example ) # shows examples
		example
		;;
	-l|--list ) # shows list of suras from the index
		sed -n '1,117p' $file_dir | $pager
		;;
	* ) break
		;;
esac

# Digit interpretation

# General 
echo $1 | grep -q "^[[:digit:]]\+$"
[ "$?" = 0 ] && \
	grep -w3 "^\[$1:*" $file_dir | \
	sed 's/^\[.*:\(.*\)\]\s\(.*\)/\n\n[\1] \2/g' | \
	$pager && [ -f $sura_file ] && rm $sura_file

# Show verse
echo $1 | grep -q "^[[:digit:]]\+:[[:digit:]]\+$"
[ "$?" = 0 ] && echo "$1" | sed 's/\(.*\):.*/\1/g' | \
	xargs -I '{}' grep -m1 "^{}\.\s" $file_dir> $sura_file && \
	opening_msg && \
	grep "\[$1\]" $file_dir>> $sura_file && \
	$pager $sura_file && rm $sura_file

# Verse range
echo $1 | grep -q "^[[:digit:]]\+:[[:digit:]]\+-[[:digit:]]\+$"
[ "$?" = 0 ] && \
	chapter="$(echo $1 | cut -d ':' -f1)" && \
	from="$(echo $1 | sed 's/.*:\(.*\)-.*/\1/g')" && \
	to="$(echo $1 | sed 's/.*-\(.*\)/\1/g')" && \
	grep -m1 "^$chapter\.\s" $file_dir> $sura_file && \
	verse_loop && $pager $sura_file && rm $sura_file

# chapter range
echo $1 | grep "^[[:digit:]]\+-[[:digit:]]\+$" | grep -q -v ":"
[ "$?" = 0 ] && \
	schapter="$(echo $1 | cut -d '-' -f1)" && \
	echapter="$(echo $1 | cut -d '-' -f2)" && \
	chapter_loop && $pager $sura_file && rm $sura_file

# Alphabetical interpretation

# General
echo $1 | grep -q "^[[:alpha:]]\+$"
[ "$?" = 0 ] && \
	achapter="$(grep -i -m1 "$1" $file_dir | cut -d '.' -f1)" && \
	grep -w3 "^\[$achapter:*" $file_dir | \
	sed 's/^\[.*:\(.*\)\]\s\(.*\)/\n\n[\1] \2/g' | \
	$pager && [ -f $sura_file ] && rm $sura_file

# Show verse
echo $1 | grep -q "^[[:alpha:]]\+:[[:digit:]]\+$"
[ "$?" = 0 ] && \
	verse="$(echo $1 | cut -d ':' -f2)" && \
	chapter="$(echo $1 | cut -d ':' -f1 | \
	xargs -I '{}' grep -i -m1 "{}" $file_dir | cut -d '.' -f1)" && \
	grep -i -m1 "^$chapter\.\s" $file_dir> $sura_file && \
	opening_msg && \
	grep "\[$chapter:$verse\]" $file_dir>> $sura_file && \
	$pager $sura_file && rm $sura_file

# Verse range
echo $1 | grep -q "^[[:alpha:]]\+:[[:digit:]]\+-[[:digit:]]\+$"
[ "$?" = 0 ] && \
	chapter="$(echo $1 | cut -d ':' -f1 | \
	xargs -I '{}' grep -i -m1 "{}" $file_dir | cut -d '.' -f1)" && \
	from="$(echo $1 | sed 's/.*:\(.*\)-.*/\1/g')" && \
	to="$(echo $1 | sed 's/.*-\(.*\)/\1/g')" && \
	grep -i -m1 "^$chapter\.\s" $file_dir> $sura_file && \
	verse_loop && $pager $sura_file && rm $sura_file

# chapter range
echo $1 | grep -q "^[[:alpha:]]\+-[[:alpha:]]\+$"
[ "$?" = 0 ] && \
	schapter="$(echo $1 | cut -d '-' -f1 | \
	xargs -I '{}' grep -i -m1 "{}" $file_dir | cut -d '.' -f1)" && \
	echapter="$(echo $1 | cut -d '-' -f2 | \
	xargs -I '{}' grep -i -m1 "{}" $file_dir | cut -d '.' -f1)" && \
	chapter_loop && $pager $sura_file && rm $sura_file
